name: goapp
on: 
  push:
    branches: [ master ]
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: code-checkout
        run: |
          echo "code run successfully"
  Code_build:
    runs-on: ubuntu-latest
    needs: Code-checkout
    steps:
      - uses: actions/checkout@v2
      - name: Code Build
        run: | 
          echo "Building Code..."
          docker build -t myimage .
  Code_push:
    runs-on: ubuntu-latest
    needs: Code_build
    steps:
      - uses: actions/checkout@v2
      - name: Code Build
        run: | 
          echo "Building Code..."
          docker build -t examples .
          docker tag examples madhupdevops/two-tier-app:v2
          docker login -u ${{ secrets.dockerusername }} -p ${{ secrets.dockerpass }}
          docker push madhupdevops/two-tier-app:v2
