name: goapp
on: 
  push:
    branches: [ master ]
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: code-checkout
        run: |
          echo "code run successfully"
  Code_build:
    runs-on: ubuntu-latest
    needs: code-checkout
    steps:
      - uses: actions/checkout@v2
      - name: Code Build
        run: | 
          echo "Building Code..."
          docker build -t examples -f Dockerfile .
  Code_push:
    runs-on: ubuntu-latest
    needs: Code_build
    steps:
      - uses: actions/checkout@v2
      - name: Code Build
        run: | 
          echo "Building Code..."
          docker build -t examples -f Dockerfile .
          docker tag examples:v2
          docker login -u ${{ secrets.dockeruser }} -p ${{ secrets.dockerpass }}
          docker push examples:v2
